/**
 * Fetches public Firebase config from live Apps Script and patches service worker.
 * Run before: firebase deploy --only hosting
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const GAS_EXEC = process.env.SHOWRUNNER_GAS_EXEC
  || 'https://script.google.com/macros/s/AKfycbxynTt5JaKQiv1Iu_ahSQBcrBDKpuhz98lac4G-bJO5PMtmvgJr_uKZ1Y58lxOOupSwlw/exec';

const LOCAL_CFG_PATH = path.join(__dirname, 'firebase-public-config.json');

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        const next = res.headers.location.startsWith('http')
          ? res.headers.location
          : new URL(res.headers.location, url).href;
        return fetchText(next).then(resolve).catch(reject);
      }
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    }).on('error', reject);
  });
}

function parseJsonp(body, callbackName) {
  const prefix = callbackName + '(';
  const start = body.indexOf(prefix);
  if (start < 0) return null;
  const jsonStart = start + prefix.length;
  const jsonEnd = body.lastIndexOf(')');
  if (jsonEnd <= jsonStart) return null;
  try {
    return JSON.parse(body.slice(jsonStart, jsonEnd));
  } catch (e) {
    return null;
  }
}

async function fetchFirebaseConfig() {
  const callback = '__srFcfgPrep';
  const url = GAS_EXEC + '?action=fcfg&callback=' + encodeURIComponent(callback);
  const { body } = await fetchText(url);

  let cfg = parseJsonp(body, callback);
  if (!cfg) {
    try { cfg = JSON.parse(body); } catch (e) { /* fall through */ }
  }
  if (!cfg) {
    const preview = body.trim().slice(0, 120);
    throw new Error('Invalid config response from Apps Script: ' + preview);
  }
  if (cfg.error) {
    throw new Error('Apps Script fcfg error: ' + cfg.error);
  }
  return cfg;
}

function loadLocalConfig() {
  if (!fs.existsSync(LOCAL_CFG_PATH)) return {};
  try {
    return JSON.parse(fs.readFileSync(LOCAL_CFG_PATH, 'utf8'));
  } catch (e) {
    console.warn('Could not parse', LOCAL_CFG_PATH, '-', e.message);
    return {};
  }
}

function mergeConfig(remote, local) {
  const projectId = remote.projectId || local.projectId || 'sm-showrunner-97405';
  return {
    apiKey: remote.apiKey || local.apiKey || '',
    authDomain: remote.authDomain || local.authDomain || (projectId + '.firebaseapp.com'),
    projectId: projectId,
    storageBucket: remote.storageBucket || local.storageBucket || (projectId + '.firebasestorage.app'),
    messagingSenderId: remote.messagingSenderId || local.messagingSenderId || '',
    appId: remote.appId || local.appId || '',
    vapidKey: remote.vapidKey || local.vapidKey || ''
  };
}

async function main() {
  const publicDir = path.join(__dirname, 'public');
  const swPath = path.join(publicDir, 'firebase-messaging-sw.js');
  console.log('Fetching Firebase public config from Apps Script...');

  let remote = {};
  try {
    remote = await fetchFirebaseConfig();
  } catch (err) {
    console.warn('Remote fcfg failed:', err.message);
    console.warn('Using local fallback from firebase-public-config.json if present.');
  }

  const local = loadLocalConfig();
  const cfg = mergeConfig(remote, local);

  if (!cfg.apiKey) {
    console.warn('WARNING: apiKey empty — set FIREBASE_WEB_API_KEY in Script Properties.');
  }
  if (!cfg.messagingSenderId || !cfg.appId) {
    console.warn('WARNING: messagingSenderId or appId missing — add FIREBASE_MESSAGING_SENDER_ID + FIREBASE_APP_ID (or FIREBASE_WEB_CONFIG JSON) to Script Properties.');
  }

  const sw = `/**
 * Generated by prepare-hosting.js — service worker for FCM background messages.
 */
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify({
    apiKey: cfg.apiKey,
    authDomain: cfg.authDomain,
    projectId: cfg.projectId,
    storageBucket: cfg.storageBucket,
    messagingSenderId: cfg.messagingSenderId,
    appId: cfg.appId
  }, null, 2)});

const messaging = firebase.messaging();
const SR_PUSH_ICON = '/icon-192.png';
messaging.onBackgroundMessage(function(payload) {
  const d = payload.data || {};
  const n = payload.notification || {};
  const title = n.title || d.title || 'Showrunner';
  const body = n.body || d.body || '';
  const msg = { type: 'SHOWRUNNER_FOREGROUND_PUSH', title: title, body: body };
  return self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
    clientList.forEach(function(client) {
      try { client.postMessage(msg); } catch (e) { /* ignore */ }
    });
    const anyVisible = clientList.some(function(c) { return c.visibilityState === 'visible'; });
    if (anyVisible) return;
    return self.registration.showNotification(title, {
      body: body,
      icon: n.icon || SR_PUSH_ICON,
      badge: n.badge || SR_PUSH_ICON,
      data: d,
      tag: 'showrunner-push',
      renotify: true,
      vibrate: [180, 80, 180]
    });
  });
});
`;
  fs.writeFileSync(swPath, sw);
  console.log('Updated firebase-messaging-sw.js');
  console.log('Config project:', cfg.projectId, '| sender:', cfg.messagingSenderId || '(missing)', '| appId:', cfg.appId ? 'set' : '(missing)');
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
