/**
 * Fetches public Firebase config from live Apps Script and patches service worker.
 * Run before: firebase deploy --only hosting
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const GAS_EXEC = process.env.SHOWRUNNER_GAS_EXEC
  || 'https://script.google.com/macros/s/AKfycbzilZyZ-qzQoUPBr0Y5r1G7nGVsPMq2XTwRRfNQZTm7/exec';

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return fetchJson(res.headers.location).then(resolve).catch(reject);
      }
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error('Invalid JSON from ' + url + ': ' + data.slice(0, 200))); }
      });
    }).on('error', reject);
  });
}

async function main() {
  const publicDir = path.join(__dirname, 'public');
  const swPath = path.join(publicDir, 'firebase-messaging-sw.js');
  console.log('Fetching Firebase public config from Apps Script...');
  const cfg = await fetchJson(GAS_EXEC + '?action=fcfg');
  if (!cfg.apiKey) {
    console.warn('WARNING: apiKey empty — set FIREBASE_WEB_API_KEY in Script Properties and dev-push first.');
  }
  const sw = `/**
 * Generated by prepare-hosting.js — service worker for FCM background messages.
 */
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify({
    apiKey: cfg.apiKey,
    authDomain: cfg.authDomain,
    projectId: cfg.projectId,
    storageBucket: cfg.storageBucket,
    messagingSenderId: cfg.messagingSenderId,
    appId: cfg.appId
  }, null, 2)});

const messaging = firebase.messaging();
messaging.onBackgroundMessage(function(payload) {
  const title = (payload.notification && payload.notification.title) || 'Showrunner';
  const options = {
    body: (payload.notification && payload.notification.body) || '',
    data: payload.data || {}
  };
  self.registration.showNotification(title, options);
});
`;
  fs.writeFileSync(swPath, sw);
  console.log('Updated firebase-messaging-sw.js');
  console.log('Config project:', cfg.projectId, '| sender:', cfg.messagingSenderId || '(missing)');
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
